name: Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always
  RUST_CACHE_KEY: rust-cache-20240701
  CARGO_PROFILE_DEV_DEBUG: none

jobs:
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Check formatting
        run: cargo fmt -- --check
  doc:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.RUST_CACHE_KEY }}
      - run: sudo apt update && sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - name: Cargo doc
        run: cargo doc --no-deps
  test:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.RUST_CACHE_KEY }}
      - run: sudo apt update && sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libwayland-dev libxkbcommon-dev
      - run: cargo install cargo-all-features
      - name: Clippy for bevy_rapier2d
        run: cargo clippy --verbose -p bevy_rapier2d --examples
      - name: Clippy for bevy_rapier3d
        run: cargo clippy --verbose -p bevy_rapier3d --examples
      - name: Clippy for bevy_rapier2d (debug-render, simd, serde)
        run: cargo clippy --verbose -p bevy_rapier2d --features debug-render-2d,simd-stable,serde-serialize,picking-backend
      - name: Clippy for bevy_rapier3d (debug-render, simd, serde)
        run: cargo clippy --verbose -p bevy_rapier3d --features debug-render-3d,simd-stable,serde-serialize,picking-backend
      - name: Test for bevy_rapier2d
        run: cargo test --verbose -p bevy_rapier2d
      - name: Test for bevy_rapier3d
        run: cargo test --verbose -p bevy_rapier3d
      - name: Test for no conflicting system order ambiguity
        run: cargo run --bin ambiguity_detection
      - name: Check all features individually
        run: cargo check-all-features
  test-wasm:
    runs-on: ubuntu-latest
    env:
      RUSTFLAGS: -D warnings
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: ${{ env.RUST_CACHE_KEY }}
      - name: Clippy bevy_rapier2d
        run: cd bevy_rapier2d && cargo clippy --verbose --features bevy/webgl2 --target wasm32-unknown-unknown
      - name: Clippy bevy_rapier3d
        run: cd bevy_rapier3d && cargo clippy --verbose --features bevy/webgl2 --target wasm32-unknown-unknown
